### ISSUE TITLE
Add some details on building the wasm module.

### ISSUE THREAD

**Issue by yy-zhong** [Enter-tainer/jogs#2]
The instruction in the `build.sh` is quite clear, but some of the command in it isn't that easy to understand. 
For example, this line https://github.com/Enter-tainer/jogs/blob/fa72d8923e8cbddd792118961577bcf3f9b7db46/build.sh#L7 
uses the `wasi-stub` tool. But it lacks some information of the tool itself, like the tool is actually located in the [wasm-minimal-protocol](https://github.com/astrale-sharp/wasm-minimal-protocol).

So I suggest adding some useful information to it. ╰(*°▽°*)╯

**Comment by Enter-tainer** [comment]
i would like encourage anyone interested to add more detailed build instructions

**Comment by yy-zhong** [comment]
> i would like encourage anyone interested to add more detailed build instructions

Just made an pull request on this! 😁
